# How it works - Python NumPy

* Author: Cleiber Garcia
* Version's date: March, 2023

* Pourpose: Develop competencies on how Python NumPy works

* This Notebook was produced as part of my studies of the course 'Python for Data Science and Machine Learning Bootcamp', taught by Mr Jose Portilla, Head of Data Science at Pierian Training. The course is offered ad Udemy (https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/learn/lecture/5784218?start=15#overview). 

* Although the degree of similarity between this notebook and the notebook written by Jose Portillo for this course is almost 100%, I assure you that I wrote it line by line. Also, I took the liberty to make some changes in order to clariry some examples or to make code more readable, when I judged it apropriate.

* For more information, please contact me at cleiber.garcia@gmail.com


# 1. NumPy Arrays

## 1.1 Creating NumPy Arrays From Python Lists

In [2]:
# Importing NumPy module
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
type(my_list)

list

In [5]:
my_array_1d = np.array(my_list)
my_array_1d

array([1, 2, 3])

In [6]:
type(my_array_1d)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
type(my_matrix)

list

In [9]:
my_array_3x3 = np.array(my_matrix)
my_array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(my_array_3x3)

numpy.ndarray

## 1.2 NumPy Built-in Methods

### .arange()

Return evenly spaced values within a given interval.

In [77]:
# set an array of integer numbers from 0 to 9
np.arange(0,10) # note that the upper limit is not part of the array generated 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# set an array of integer numbers from 0 to 10, incremented by 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### .zeros()
Return an array of zeroes

In [17]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [22]:
type(a)

numpy.ndarray

In [23]:
a.shape

(3,)

In [19]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
type(b)

numpy.ndarray

In [27]:
b.shape

(5, 5)

### .ones()
Set an array of ones

In [26]:
# Print an array 3 by 1 of ones
np.ones(3)

array([1., 1., 1.])

In [25]:
# Print an array 3 by 3 of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### .linspace()
Return evenly spaced numbers over a specified interval.

In [28]:
# Set an array with 3 numbers, evenly spaced, between 0 and 10, inclusive
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
# Set an array with 5 numbers, evenly spaced, between 0 and 10, inclusive
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
# Set an array with 20 numbers, evenly spaced, between 0 and 10, inclusive
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### .eye()
Create an identity matrix

In [33]:
# Create an 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### .rand()
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [35]:
# Return an array of 2 random numbers from a uniform distribution over [0, 1)
np.random.rand(2)

array([0.56691758, 0.9071763 ])

In [37]:
# Create an array 5 by 5 populated with random samples from a uniform distribution over [0,1)
np.random.rand(5,5)

array([[0.76870578, 0.56805256, 0.85887478, 0.01173208, 0.41791433],
       [0.7392704 , 0.43923488, 0.75055528, 0.71323225, 0.23163937],
       [0.28325327, 0.03484737, 0.67901422, 0.76955265, 0.00565298],
       [0.54675994, 0.54141244, 0.45229194, 0.7247022 , 0.59607175],
       [0.32432462, 0.34840928, 0.45293997, 0.72314085, 0.21271538]])

### .randn()

Return a sample (or samples) from the "standard normal" distribution, with the given format

In [40]:
# Return an array with 2 random numbers from a standard normal distribution
np.random.randn(2)

array([-0.0591228 , -1.11282489])

In [42]:
# Return an array 5 by 5 of random numbers from a standard normal distribution
np.random.randn(5,5)

array([[ 1.18673015, -0.32840677,  0.57629407,  0.03978289,  1.8864411 ],
       [-0.33737919,  0.84166312,  0.35690297,  1.3478518 , -0.34586954],
       [-0.47869056,  0.35801233,  0.06167865, -0.89863338, -0.01167345],
       [-1.13422383, -0.80539925,  0.43349417, -2.01116898, -0.49740418],
       [ 0.14973633,  0.40425114, -0.77735408, -1.56647423,  0.7631094 ]])

### .randint()
Return random integers from `low` (inclusive) to `high` (exclusive).

In [44]:
# Return one random integer from 1 (inclusive) to 100 (exclusive)
np.random.randint(1,100)

45

In [45]:
# Return ten random integers from 1 (inclusive) to 100 (exclusive)
np.random.randint(1,100,10)

array([ 4, 87, 54, 22, 12, 48, 76, 87, 44, 60])

## 1.3 Array Attributes and Methods

In [47]:
# Return a sequance of integer numbers between 0 (inclusive) and 25 (exclusive)
my_array = np.arange(25)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
# Return 10 integer random numbers between 0 (inclusive) and 50 (exclusive)
my_random_array = np.random.randint(0,50,10)
my_random_array

array([21, 19, 39,  6, 18, 11, 20, 23, 49, 43])

### .reshape()
Returns an array containing the same data with a new shape.

In [57]:
# Reshape my_array from (25,) to (5,5) 
my_reshape_array = my_array.reshape(5,5)
my_reshape_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
my_array.shape

(25,)

In [58]:
my_reshape_array.shape

(5, 5)

### .max(), .min(), .argmax(), .argmin()

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [62]:
print(my_random_array)

[21 19 39  6 18 11 20 23 49 43]


In [59]:
# Return the maximum value from my_random_array
my_random_array.max()

49

In [60]:
# Return the position of the maximum value from my_random_array
my_random_array.argmax()

8

In [63]:
# Return the minimum value from my_random_array
my_random_array.min()

6

In [65]:
# Return the position of the minimum value from my_random_array
my_random_array.argmin()

3

### .shape

Shows the shape of the array. It is an attribute that arrays have (not a method)

In [68]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
# my_array is a vector with 25 components
my_array.shape

(25,)

In [69]:
my_array.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
my_array.reshape(1,25).shape # 1 row by 25 columns

(1, 25)

In [71]:
my_array.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [72]:
my_array.reshape(25, 1).shape # 25 rows x 1 column

(25, 1)

### .dtype

To grab the data type of the object in the array

In [73]:
# Show the type of the elements of the array my_array
my_array.dtype 

dtype('int32')

In [75]:
# Show the data type of my_array
type(my_array)

numpy.ndarray

# 2. NumPy Array Indexing and Selection
Indexing and selecting elements or groups of elements from an array

In [2]:
import numpy as np

In [3]:
#Creating a sample array with integer numbers from 0 to 10
arrayX= np.arange(0,11)
arrayX

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2.1 Bracket Indexing and Selection
Permits to pick one or some elements of an array in a way similar to python lists

In [4]:
#Get a value at an index
arrayX[8]

8

In [5]:
#Get values in a range
arrayX[1:5]

array([1, 2, 3, 4])

## 2.2 Broadcasting

Setting values with index range

In [6]:
#Setting a value with index range (Broadcasting)
arrayX[0:5]=100
arrayX

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
# Resetting arrayX
arrayX = np.arange(0,11)
arrayX

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2.3 Slicing
Data is not copied unless explicitly asked. Both arrays will point to the same memory address

In [8]:
# Creating a new array from slicing another one
slice_of_arrayX = arrayX[0:6]
slice_of_arrayX

array([0, 1, 2, 3, 4, 5])

In [9]:
#Change Sliced array
slice_of_arrayX[:]=99
slice_of_arrayX

array([99, 99, 99, 99, 99, 99])

In [10]:
# arrayX was also modified
arrayX

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [11]:
#To get a copy, we need to be explicit
arrayX_copy = arrayX.copy()
arrayX_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
type(arrayX_copy)

numpy.ndarray

In [13]:
arrayX_copy[:] = 88
arrayX_copy

array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [14]:
arrayX # arrayX was not affected by the al

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2.4 Indexing a 2D array (matrices)
To get the element at position rowX and columnY, we can use both array_2d[rowX, columnY] and array_2d[rowX][columnY]

In [70]:
# Setting up array_2d as a 3 by 3 matrix
array_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
# Print the first line of array_2d
array_2d[0]

array([ 5, 10, 15])

In [17]:
# Print the second column of array_2d
array_2d[:,1]

array([10, 25, 40])

In [27]:
# Print the elements of the main diagonal (elements of M_ixj for which i=j)
for i in [0,1,2]:
    j = i
    print(array_2d[i,j]) 

5
25
45


In [28]:
# Print the elements of the main diagonal (elements of M_ixj for which i=j)
for i in [0,1,2]:
    j = i
    print(array_2d[i][j]) 

5
25
45


In [26]:
# Getting the element at the second row and at the first column
array_2d[1,0]

20

In [25]:
# Alternative way to get the element at the second row and at the first column
array_2d[1][0]

20

In [29]:
print(array_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [32]:
#Shape (2,2) from top right corner
array_2d[:2,1:] # row indexes: 0 (first), 1 (second) and 2 (third); column indexes: 0 (first), 1 (second) and 2 (third)

array([[10, 15],
       [25, 30]])

In [33]:
#Print the botton row
array_2d[2]

array([35, 40, 45])

### Fancy Indexing
Fancy indexing allows us to select entire rows or columns out of order

In [42]:
#Set up array_A as a matrix 10 by 10
array_A = np.zeros((10,10))
array_A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
# Print array shape
array_A.shape

(10, 10)

In [44]:
#Length of array
array_length = array_A.shape[0]
array_length

10

In [46]:
#Set up array

for i in range(array_length):
    array_A[i] = i
    
print(array_A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [47]:
array_A[[2,4,6,8]] # print third, fifth, seventh and ninth rows

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [49]:
array_A[[6,2,8, 4]] # print seventh, third, ninth and fifth rows

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

### Selection based on comparison operators

In [54]:
# Set array_B with integer numbers from 1 to 10
array_B = np.arange(1,11)
array_B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# test if array_B values are greater than 4
array_B > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
# Print array_B values greater than 4
mask = array_B > 4
array_B[mask]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
# Print array_B values greater than 4
array_B[array_B > 4]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
# Print array_B values greater than 2
array_B[array_B > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
# Print array_B values greater than 2
mask = array_B > 2
array_B[mask]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# 3. NumPy Operations

In [103]:
# importing NumPy module
import numpy as np

## 3.1 Arithmetic Operations Over Arrays

In [93]:
# Setting up array_C with integer numbers from 0 to 9
array_C = np.arange(0,10)
array_C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# Add 5 to array_C
print(array_C + 5)

[ 5  6  7  8  9 10 11 12 13 14]


In [95]:
# Add array_C to itself (doubling its values)
print(array_C + array_C)

[ 0  2  4  6  8 10 12 14 16 18]


In [96]:
# Subtract 3 from array_C
print(array_C - 3)

[-3 -2 -1  0  1  2  3  4  5  6]


In [97]:
# Subtract array_C by itself
print(array_C - array_C)

[0 0 0 0 0 0 0 0 0 0]


In [98]:
# Multiply array_C by 2
print(array_C * 2)

[ 0  2  4  6  8 10 12 14 16 18]


In [99]:
# Multiply array_C by itself (squaring its values)
print(array_C * array_C)

[ 0  1  4  9 16 25 36 49 64 81]


In [100]:
# Square array_C
print(array_C ** 2)

[ 0  1  4  9 16 25 36 49 64 81]


In [101]:
# Divide array_C by 2
print(array_C / 2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [102]:
# Divide array_C by itself
print(array_C / array_C)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\PC-IO\AppData\Local\Temp\ipykernel_1416\229368034.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(array_C / array_C)


## 3.2 NumPy Mathematical Functions Over Arrays

In [104]:
print(array_C)

[0 1 2 3 4 5 6 7 8 9]


In [105]:
#Taking Square Roots
np.sqrt(array_C)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [107]:
#Calcualting exponential (e^)
np.exp(1) # e^1

2.718281828459045

In [109]:
np.exp(array_C) # e^array_C

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [113]:
# Printing the maximum value of array_C
np.max(array_C) #same as array_C.max()

9

In [116]:
# Printing the maximum value of array_C
array_C.max()

9

In [115]:
# Print trigonometric sin of array_C values
np.sin(array_C)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [124]:
# Print trigonometric sin of array_C values
sin_values = []
for i in [0,1,2,3,4,5,6,7,8,9]:
    sin_values.append(np.sin(i))
print(sin_values)

[0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586, 0.6569865987187891, 0.9893582466233818, 0.4121184852417566]


In [129]:
# Print the natural logarithm of e = 2.718281828459045...
print(np.log(2.718281828459045)) 

1.0


In [130]:
# Print the natural logarithm of array_C values
print(np.log(array_C))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\PC-IO\AppData\Local\Temp\ipykernel_1416\2055191436.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(array_C))


In [131]:
# Print the natural logarithm of array_C values
log_values = []
for i in [0,1,2,3,4,5,6,7,8,9]:
    log_values.append(np.log(i))
print(log_values)

[-inf, 0.0, 0.6931471805599453, 1.0986122886681098, 1.3862943611198906, 1.6094379124341003, 1.791759469228055, 1.9459101490553132, 2.0794415416798357, 2.1972245773362196]


C:\Users\PC-IO\AppData\Local\Temp\ipykernel_1416\733379825.py:4: RuntimeWarning: divide by zero encountered in log
  log_values.append(np.log(i))
